CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_AUDIT_ERR_AI_SYS_SEC_READLOG_ERRORS" 
BEFORE INSERT OR UPDATE ON "AI_SYS_SEC_READLOG_ERRORS" 
FOR EACH ROW 
BEGIN 
    IF INSERTING THEN 
        :NEW.CREATED_AT      := SYSTIMESTAMP; 
        :NEW.CREATED_BY_USER := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER); 
    END IF; 
    IF UPDATING THEN 
        :NEW.UPDATED_AT      := SYSTIMESTAMP; 
        :NEW.UPDATED_BY_USER := NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), USER); 
    END IF; 
END;
/
ALTER TRIGGER "TRG_AUDIT_ERR_AI_SYS_SEC_READLOG_ERRORS" ENABLE;
