CREATE OR REPLACE TRIGGER "TRG_AI_SEC_RAG_DELETE_BASIC_SEC_T_DIAGNOSIS"  
    AFTER DELETE ON BASIC_SEC_T_DIAGNOSIS  
    FOR EACH ROW  
BEGIN  
    DELETE FROM AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENTS  
    WHERE source_type = 'DIAGNOSIS'  
      AND source_id = :OLD.DIAGNOSISID;  
EXCEPTION  
    WHEN OTHERS THEN  
        BEGIN  
            ERROR_LOG_PKG_SYSTEM_ALL.INSERT_AI_SYS_SEC_LOG(SQLERRM, 'trg_ai_sec_rag_delete_diagnosis', NVL(v('APP_USER'),'SYSTEM'));  
        EXCEPTION  
            WHEN OTHERS THEN NULL;  
        END;  
END;
/

CREATE OR REPLACE TRIGGER "TRG_AI_SEC_RAG_DELETE_BASIC_SEC_T_MEDICALREPORT"  
    AFTER DELETE ON BASIC_SEC_T_MEDICALREPORT  
    FOR EACH ROW  
BEGIN  
    DELETE FROM AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENTS  
    WHERE source_type = 'REPORT'  
      AND source_id = :OLD.REPORTID;  
EXCEPTION  
    WHEN OTHERS THEN  
        BEGIN  
            ERROR_LOG_PKG_SYSTEM_ALL.INSERT_AI_SYS_SEC_LOG(SQLERRM, 'trg_ai_sec_rag_delete_report', NVL(v('APP_USER'),'SYSTEM'));  
        EXCEPTION  
            WHEN OTHERS THEN NULL;  
        END;  
END;
/

CREATE OR REPLACE TRIGGER "TRG_AI_SEC_RAG_DELETE_BASIC_SEC_T_TREATMENT"  
    AFTER DELETE ON BASIC_SEC_T_TREATMENT  
    FOR EACH ROW  
BEGIN  
    DELETE FROM AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENTS  
    WHERE source_type = 'TREATMENT'  
      AND source_id = :OLD.TREATMENTID;  
EXCEPTION  
    WHEN OTHERS THEN  
        BEGIN  
            ERROR_LOG_PKG_SYSTEM_ALL.INSERT_AI_SYS_SEC_LOG(SQLERRM, 'trg_ai_sec_rag_delete_treatment', NVL(v('APP_USER'),'SYSTEM'));  
        EXCEPTION  
            WHEN OTHERS THEN NULL;  
        END;  
END;
/

CREATE OR REPLACE TRIGGER "TRG_AI_SEC_RAG_DELETE_BOOKING_SEC_T_APPOINTMENT"  
    AFTER DELETE ON BOOKING_SEC_T_APPOINTMENT  
    FOR EACH ROW  
BEGIN  
    DELETE FROM AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENTS  
    WHERE source_type = 'APPOINTMENT'  
      AND source_id = :OLD.APPOINTMENTID;  
EXCEPTION  
    WHEN OTHERS THEN  
        BEGIN  
            ERROR_LOG_PKG_SYSTEM_ALL.INSERT_AI_SYS_SEC_LOG(SQLERRM, 'trg_ai_sec_rag_delete_appointment', NVL(v('APP_USER'),'SYSTEM'));  
        EXCEPTION  
            WHEN OTHERS THEN NULL;  
        END;  
END;
/

CREATE OR REPLACE TRIGGER "TRG_AI_SEC_RAG_DELETE_LAB_SEC_T_RESULTS"  
    AFTER DELETE ON LAB_SEC_T_RESULTS  
    FOR EACH ROW  
BEGIN  
    DELETE FROM AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENTS  
    WHERE source_type = 'LAB_RESULT'  
      AND source_id = :OLD.RESULTID;  
EXCEPTION  
    WHEN OTHERS THEN  
        BEGIN  
            ERROR_LOG_PKG_SYSTEM_ALL.INSERT_AI_SYS_SEC_LOG(SQLERRM, 'trg_ai_sec_rag_delete_lab_results', NVL(v('APP_USER'),'SYSTEM'));  
        EXCEPTION  
            WHEN OTHERS THEN NULL;  
        END;  
END;
/

CREATE OR REPLACE TRIGGER "TRG_AI_SEC_RAG_DELETE_RADIOLOGY_SEC_T_RADIOLOGYRESULTS"  
    AFTER DELETE ON RADIOLOGY_SEC_T_RADIOLOGYRESULTS  
    FOR EACH ROW  
BEGIN  
    DELETE FROM AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENTS  
    WHERE source_type = 'RADIOLOGY_RESULT'  
      AND source_id = :OLD.RESULTID;  
EXCEPTION  
    WHEN OTHERS THEN  
        BEGIN  
            ERROR_LOG_PKG_SYSTEM_ALL.INSERT_AI_SYS_SEC_LOG(SQLERRM, 'trg_ai_sec_rag_delete_radiology_results', NVL(v('APP_USER'),'SYSTEM'));  
        EXCEPTION  
            WHEN OTHERS THEN NULL;  
        END;  
END;
/
