-- Vector index creation scripts for Oracle 23ai / 26ai

-- Create Vector Index on the Document embeddings
-- Note: Replace with exact vector dimensions and metrics as needed
CREATE VECTOR INDEX IDX_AI_EMBEDDING ON AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENTS(EMBEDDING)
ORGANIZATION INMEMORY NAVIGABLE SMALL WORLD (HNSW)
DISTANCE COSINE
WITH TARGET ACCURACY 95;

-- Create Vector Index on the Chunk embeddings
CREATE VECTOR INDEX IDX_AI_CHUNK_EMBEDDING ON AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENT_CHUNKS(EMBEDDING)
ORGANIZATION INMEMORY NAVIGABLE SMALL WORLD (HNSW)
DISTANCE COSINE
WITH TARGET ACCURACY 95;
