-- Oracle Vector Search RAG Toolkit Uninstallation Script

PROMPT Dropping Packages...
DROP PACKAGE AI_SEC_RAG_SYSTEM_ALL;
DROP PACKAGE AI_SEC_RAG_SYSTEM_ALL_SUB_ADMIN_PKG;
DROP PACKAGE AI_SEC_RAG_SYSTEM_ALL_SUB_SYNC_PKG;
DROP PACKAGE AI_SEC_RAG_SYSTEM_ALL_SUB_SEARCH_PKG;
DROP PACKAGE AI_SEC_RAG_SYSTEM_ALL_SUB_DAO_PKG;
DROP PACKAGE AI_SEC_RAG_SYSTEM_ALL_SUB_EMBED_PKG;
DROP PACKAGE AI_SEC_RAG_SYSTEM_ALL_SUB_UTIL_PKG;
DROP PACKAGE AI_SEC_RAG_SYSTEM_ALL_SUB_ERR_HANDLER_PKG;

PROMPT Dropping Views...
DROP VIEW AI_SEC_SYS_VIEW_PATIENT_FULL_HISTORY_LOOKUP;

PROMPT Dropping Tables...
DROP TABLE AI_SEC_RAG_SYSTEM_L_EVENT CASCADE CONSTRAINTS;
DROP TABLE AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENT_CHUNKS CASCADE CONSTRAINTS;
DROP TABLE AI_SEC_RAG_SYSTEM_L_HELP_AI_DOCUMENTS CASCADE CONSTRAINTS;
DROP TABLE AI_SYS_SEC_READLOG_ERRORS CASCADE CONSTRAINTS;

PROMPT Uninstallation Complete.
